### PR TITLE
Issue #3083980 by chmez: Push notifications provider

### PR DESCRIPTION
**Pull request by OH17L**
## Problem
When I want to use some custom provider of push notifications together with (or separate) PWA provider from this module then I can not create some settings wrapper on the user settings page.

## Solution
Update settings section for the user edit page based on a new plugin which will be created [here](https://github.com/goalgorilla/open_social/pull/1509).

## Issue tracker
- https://www.drupal.org/project/social_pwa/issues/3083980
- https://getopensocial.atlassian.net/browse/ECI-921

### CODE REVIEW

**Comment by ronaldtebrake** [comment]
Hey guys, this looks good to me :) 
We could add a required version to OS in our composer.json, just to ensure people have the correct versions. 
(We will be able to release it in ^7.2) 

would that be an idea @ribel @OH17L

**Comment by ribel** [comment]
Yes, as discussed we will add this in this PR.

**Comment by OH17L** [comment]
@ronaldtebrake, which account should I use for distro in the **composer.json** file - **drupal** (**_"drupal/open_social": "^7.2"_**) or **goalgorilla** (**_"goalgorilla/open_social": "^7.2"_**)?

**Comment by ronaldtebrake** [comment]
@OH17L "drupal/open_social": "^7.2" would be best, thanks!

**Pull request merged**
